---
default:
  general:
    # this will be merged to the remote and local section
    general_log: ./logs/general.log

  remote:
    # settings for the commands that will be run remotely
    log:
      app: /var/log/app/app.log
      queue: /var/log/app/app-queue.log
    reload_script: /usr/local/bin/app_reload
    restart_script: /usr/local/bin/app_restart
    pre_run: echo 'no reset dir script'
    post_run: /usr/local/bin/app_status

  local:
    # settings for the commands that will be run localy
