---
default:
  general:
    # this will be merged to the remote and local section
    general_log: ./logs/general.log

  remote:
    # settings for the commands that will be run remotely
    log:
      noodoo: /var/log/noodoo/noodoo.log
      queue: /var/log/noodoo/queue.log
    reload_script: /usr/local/bin/noodoo_reload
    restart_script: /usr/local/bin/noodoo_restart
    pre_run: echo 'no reset dir script'
    post_run: /usr/local/bin/noodoo_status

  local:
    # settings for the commands that will be run localy